import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Fleet partners from Redash query 4845 (partner_entity_name)
// Fetched on 2026-01-30
const suppliers = [
  " المهم لنقل البري",
  "ABU BAKER",
  "ABU FARIS",
  "ABUDAWOOD LOGISTICS",
  "AFTAB",
  "AJEX",
  "AL BARRAK LOGITICS SERVICE  CO LTD",
  "AL GHAZAL TRANSPORT",
  "AL MAQATI TRANSPORT",
  "AL-Muhaiamzi Transportation",
  "AL.ADhAM",
  "ALAHDAF UNITED LOGISTICS",
  "ALS",
  "ALTURUQ ALMUMAHADA",
  "ALZAFAR GROUP",
  "ARABIAN BRIDGES TRANSPORT CO",
  "ASHAD ALI (GECS )",
  "ASW Transport",
  "Aamar Alhgaz",
  "Abdalah Naser Al Sahli",
  "Abdul Aziz AL-Qashami",
  "Abdul Aziz khaildi Transport EST",
  "Abdul Mohsen Alharbi Transport",
  "Abdul Rahman",
  "Abdul Razeq",
  "Abdullah Al Sahli Transport",
  "Abdullah Mohammad El Kherif Transportation Establishmen",
  "Abdullah Sadeeq (Abu Ahmed)",
  "Abdullah abdulrahman Al Ata\'allah Transport Est.",
  "Abdulraouf AL Hashmi Io champion",
  "Aber El Hadesa",
  "Aboor Tareeq",
  "Abozaid",
  "Abr Al Masarat",
  "Abr al watan ",
  "Abu Sarhad",
  "Abu Shumail Qtr",
  "Adso",
  "Advanced Tracks",
  "Afex Transportation Co.",
  "Ahmad Driver Champion",
  "Ahmad Ibrahim Champion",
  "Ahmad Shah Io champion",
  "Ahmad dossary  Transport",
  "Ahmali Transportation",
  "Ahmed",
  "Ahmed (HADICO)",
  "Ahmed M. Al Hamami Est.",
  "Ahmeed",
  "Ahtmam",
  "Aida Muhammad Mareizq Al-Rashidi",
  "Aisha Saad Almotairi transport",
  "Al - Jabri Logistics - New",
  "Al Ajmi Sons",
  "Al Baazi Transport",
  "Al Bader Transport",
  "Al Bahri Logistics",
  "Al Barq",
  "Al Fadhel transport",
  "Al Haqbani Transport",
  "Al Harbi Transport - Jay Mark",
  "Al JERI",
  "Al Jabri Logistics",
  "Al Jehran",
  "Al Jussour Group",
  "Al Khalaf",
  "Al Khamaisy Transport",
  "Al Maha Transport",
  "Al Mahri",
  "Al Manyh Transport",
  "Al Mazaid",
  "Al Nafood Al Mutkamilh",
  "Al Qulayyib Transportation",
  "Al Rashed Transport",
  "Al Rogi Transportation",
  "Al Safa\'a International Transport Est.",
  "Al Safah Transporter",
  "Al Saif Transport",
  "Al Sawat Transport",
  "Al Shalawi Logistics",
  "Al Sudais Logistics Co.",
  "Al Tawredat",
  "Al Turuq Al Thalatha logistics",
  "Al Wahshab Transport",
  "Al Wefaq Transport",
  "Al Wosool",
  "Al jahlan Io champion",
  "Al-Abraqin Al-Tawil Company",
  "Al-Barjas Al-Oula Transportation",
  "Al-Hadi Trading Est",
  "Al-Mazaani Transport",
  "Al-Washam Transport",
  "AlFatras al tayir (FMT)",
  "AlHamoudi Transport",
  "AlHaqbani For Transport Est",
  "AlRiyadah  Transportation",
  "AlShekhs Transport",
  "Alabrken Transporter",
  "Alam Alengaz",
  "Alarbiya (Ahmad Rashe)",
  "Alarbya almthda",
  "Albasami International",
  "Aldughayri Land Transport Est.",
  "Alfa شركه الفا مستقيم",
  "Alfadel Io Champion",
  "Ali",
  "Ali Abdullah Attaullha Transporter",
  "Ali Marzouq Abdullah (AMA)",
  "Ali Raza DELTA Transportation Co. LTD",
  "Alia Saleh Al Malki Land Transport Est.",
  "Alishad Transport",
  "Aljabal Int\'l Est for Transportation",
  "Almajdouie",
  "Almana io Champ",
  "Almaqtorat Alshamela LTD CO.",
  "Almarkb International Marine Service",
  "Almasder",
  "Alpha",
  "Alzyab",
  "Amir IO Champion",
  "Amir maqsood",
  "Amwaj Al Dilam Transport",
  "Anoud Najd Transport",
  "Ansaf Alhaq Transport Organization",
  "Arabain trucks",
  "Arabex Express Transport",
  "Artem Transportaion",
  "Asaf Al Khail Transporter",
  "Ashraf Ibrahim IO Champion",
  "Assas Transport",
  "Atheryoun",
  "Awad Awaad Al Rasheedi Transport",
  "Awad Jarallah Logistics",
  "Awais Khan (Speedex)",
  "Awsa",
  "Axis Logistics",
  "Azhar Cargo Transport",
  "Aziz Subhi Transportation",
  "Azmat FP",
  "Azmell",
  "BADR ALSABEI TRANSPORT",
  "BAFCO",
  "BHAVYA HAULAGE SERVICES",
  "BS Logistic Cell",
  "BST",
  "BZC",
  "Babar IO Champ",
  "Babar Transport",
  "Bakhashab Transport",
  "Baloch",
  "Bashir rafaay",
  "Bassam Shipping",
  "Bawaqar",
  "Bin Dajim Logistics",
  "Bin Dajim Transportation",
  "Bin Hannan",
  "Bindary Partner - Test",
  "Binzager (BLC)",
  "Bluelines Transport Company",
  "Carmel Group Logistics Co.",
  "City Link Group of Companies",
  "Consolidated plus",
  "DALBIR SINGH IO Champ",
  "DEACTIVATED Abo Elez",
  "DRIVER CHAMPION",
  "DURRAT",
  "Daily Logistics Services",
  "Dawn Al Fajr Logistics",
  "Delta Infora Global Logistics",
  "Demas Al Arabia Transport",
  "Demas United",
  "Demo Partner Entity",
  "Doctor",
  "Driver Champion",
  "Droob Al Safar Est.",
  "Droob Watany Transportion",
  "Durah Najad",
  "ECON",
  "EHSAAN SOORI",
  "Eastern Union",
  "Eissa - Qatara",
  "El Dawlia Group",
  "Elegant Lines (Reefers)",
  "Emar Al Madhina",
  "Emdad alkhaleej arabi",
  "Emmdad Logistic Services",
  "Energize",
  "Enjaz Al Barakah",
  "Enjaz Kian",
  "Esnad & emdad contracting transport co.",
  "European",
  "FADAH WASEA TRASPORT",
  "FAIR DEAL",
  "FAST & ACCURATE",
  "FHS",
  "FM Transport",
  "FTE LOGISTICS",
  "Factory Ksa",
  "Fahd Al Ajame Transport",
  "Faisal Al-Zanbqi Transport Est",
  "Faisal Reefer",
  "Faiz Pia Bashir IO CHAMP",
  "Faris (Al Rawabit)",
  "Fast Handling Transport",
  "Fast Track for Transport Co.",
  "FastRoad logistics Services",
  "Fawaz Khalaf Al Enazi Transportation Est",
  "Fayliq Transport Est",
  "Fayz off Co.",
  "Fazie Logistics",
  "First Gulf Logistics",
  "First International Transport",
  "First Line Transport",
  "First Middle East Transport",
  "Freight logistics solutions transport Co.",
  "Future Line Cargo by (LLC)",
  "GH Transport",
  "GLOBAL TIME",
  "GSTC",
  "Geeli Champion",
  "Ghulam Sarwar Shaf load",
  "Global Arrow Transportation",
  "Global freight nerd",
  "Globwin Logistics",
  "Go Fast",
  "Golden Logistics",
  "Golden Logistics (khaild al-mujlib)",
  "Golden Ways Logistics",
  "Golden inspiration contracting",
  "Ground lines Transport",
  "Gujjar Champion",
  "Gulf Code",
  "HARSH TRANSPORT BY HEAVY & LIGHT TRUCKS (L.L.C)",
  "HASCO",
  "Hadi Mufleh Transport",
  "Hajri Rentals",
  "Hammash Mohammed Al-Anzi CO.",
  "Hanif IO Champ",
  "Haya Halo (Khalaf)",
  "Hayat Transportation",
  "Haybah Alsharq Transport",
  "Hazaa Alhajri Group",
  "Hazim Transport",
  "Hebat alshark",
  "Hebba Transport",
  "Het Transports",
  "Hizam M.Al-Qahtani Co.",
  "Horizan Makers",
  "Horizon Maker Logistics",
  "Hussain Mohammed Hijazi",
  "Hussein Al-Madan Customs Clearance Establishment",
  "IACC",
  "IFTEKHAR IO CHAMP",
  "IMA",
  "IMC",
  "IO CHAMP",
  "IO CHAMPION",
  "IO Champ",
  "IO Champion",
  "IO Champion ",
  "IO Champion (Ali Hassan bin jassim Al Oufy )",
  "IO champ",
  "Iftikhar Ahmed XB champ",
  "Infinity Transport",
  "Injaz almhmat",
  "Inma Land Transportation",
  "International Transportion",
  "Io champion",
  "Irfan Ahmed ",
  "JAMAL KHAN WA SOAIB TRANSPORT LLC",
  "JOY",
  "JSR LOGISTICS",
  "JV KSA",
  "Jaber Al Afifi Transport",
  "Jadeer Logistics Services",
  "Jalal Ali Atif Contracting Co.",
  "Jassar Riyadh",
  "Jazirah Al Toot",
  "KANOO TERMINAL SERVICES LTD",
  "KHALID DAFER TRANSPORT (KDL)",
  "KSA TRELLA XB",
  "KSA Trella XBs (Dont Use)",
  "Kanwal Shahzadi IO Champ",
  "Kerwa logistics",
  "Khaleej AlJazeera - Abdullah ",
  "Khalid & Co. Transport Services",
  "Khalid Transport (KLC)",
  "Khalidi Transport Est",
  "Khamisy",
  "Khirat al bilaadi ",
  "LAFTAIN SINGH",
  "LONGPATH FOR TRANSPORTATION",
  "LSC",
  "LSC FREIGHT",
  "LSC Logistics",
  "Land Factors",
  "Latifa obaid Al Aswad Al Anezy",
  "Logipoint",
  "Logistics Solutions",
  "Luqmani Transport",
  "M.Star Transport Services",
  "MAMAS",
  "MANTRI CARGO TRANSPORT ",
  "MAXON Transport",
  "MDT",
  "MIRAGE TPT",
  "MOAZ AL FADHEL LOGISTICS",
  "MOHAMMAD SALAH ALHARBI",
  "MQS",
  "Maaz Asrar Alrifa",
  "Maersk",
  "Magnoony",
  "Mahawer Al Imdad Est.",
  "Mahdi bin Abdullah M. Jabara",
  "Mahmood",
  "Mahmoud Faraj (Sunbulah Transport)",
  "Majdouie Logistics Company",
  "Majid Nage",
  "Masafat Transportation EST.",
  "Masar Al Etijah Transport Establishment",
  "Masar Logistics",
  "Mashaall",
  "Mashari albilaad",
  "Masroor Ahmad Peer Bakhsh IO",
  "Maven Transport",
  "Maxxon Transport",
  "Mediator Logistics",
  "Mine",
  "Mithaq Al Sharqia Transport Co. (MSTC)",
  "Modern Gates",
  "Mohammad Zafer",
  "Mohammd Asif (Al-Dera)",
  "Mohammed Abdullah Neda Al Rashidi For Transport. Est",
  "Mohammed hamad Alhwail transport co.",
  "Momentum Logistics",
  "Mona Al Ghamdi transportation",
  "Mosal Al Shamil Logistics",
  "Mosasa Al Musharii Transportation",
  "Moverz",
  "Mubarrad",
  "Muhammad Al-Adly",
  "Muhammad Al-Hussein Abu Waddah",
  "Muneer Trading",
  "Muntansar FP",
  "Murjan Alsharqiya Co.",
  "Musa Champ",
  "Musaed Almotairi Io champion",
  "Mustafa Al Muhzami Transport",
  "NA",
  "NAQEL",
  "NAQLEEN CO LTD",
  "NAQLIY TRANSPORT AND LOGISTICS",
  "NOF Otaibi",
  "NTF Group",
  "Nahdi Transport Company",
  "Nahid Rushdee",
  "Nahj Lyan",
  "Nahran",
  "Najeeb M. Al-Hajri",
  "Najma Al Asimah Transportation",
  "Nakbat Almater",
  "Naqelat Alwasta",
  "Nasser Al Hajri transport",
  "Nasser Rashidi Transport",
  "National Transport co.",
  "Nawaf Samar Almutairi EST",
  "Nemer Al Bunyan Transport Est",
  "New Falcon",
  "Noor Al Mustaqbal",
  "Noora Jaber Al Harthi EST",
  "Nour Delivery Truckkon",
  "Noura Abdullah Al-Mutairi",
  "Noura El Harby",
  "Numan Logestics",
  "OSAMA RAGAB",
  "OSUS AL MOHAMMADIA HOLDING",
  "OTEX",
  "Obaid Munoor Mutairi Transport",
  "Ocean Tiger UAE",
  "OneSpeed Transportation",
  "Orient Entrance logistics",
  "Otaibi Transport",
  "Pak Punjab Gen Transport LLC.",
  "Palm Logistics",
  "Pankaj",
  "Parkour",
  "Prime Logistics",
  "Prime Progressive Logistics Co",
  "Qasim Qaisar Io Champion",
  "Qawafil Transportation Co.",
  "Qawi Al Jazeera",
  "RAFIQ TRANSPORT",
  "RAUF DUBAI",
  "Rakab Al Shirq Transport",
  "Rakan Transport",
  "Raqeeb Champion",
  "Rasayat Transportation Est.",
  "Rashid Al Dosary Transportation",
  "Rawasi Al-Majed Transport",
  "Rawasi AlJazira",
  "Red Sea Transport",
  "Red Target Transportation",
  "Reliable Movement Logistics",
  "Remal Al Jazeera Co",
  "Remal Al Shara\'a Transport Est.",
  "Rmada United Holding Company",
  "Rokn Al Awad transport",
  "Rouf Transport",
  "Royal transport",
  "Rumooz Alsharq transport",
  "SAMIRA MORDAD HAMDAN AL  SARWANI TRANSPORTATION EST",
  "SAUDI BULK TRANSPORT (SBT) Rentals",
  "SGS",
  "SHIPCO",
  "SMB(saeed Al Basami)",
  "SMG",
  "SULTAN TRANSPORT",
  "Saad Saif Alnaimi",
  "Sabaq Al Torooq (SAT)",
  "Saded Al Toroq Transport",
  "Sadeq Mustafa",
  "Safwa Transport",
  "Said Elmahalawy (Gulf Miles)",
  "Salasel Logistics Company",
  "Saleem mukhtar Heavy transports LLC",
  "Saleh AL Mutawa Transport",
  "Saleh Al-Dohan Est.",
  "Saleh Alawad",
  "Salem Champion",
  "Salman Alatallah",
  "Sama Al Watan Transport",
  "Sameer Dharwar(RM Logistics)",
  "Sanad Al Harbi Transport",
  "Sandeep (Nahdat Asiya)",
  "Saqib Ayedh Champion",
  "Sardar Shah",
  "Sathish io champion",
  "Saud hamad  Al khaladi",
  "Saudi Azda Transportation",
  "Saudi Wasl limited Co.",
  "Shabeeb",
  "Shahbaz Codruk",
  "Shahdab Goods",
  "Shaheen",
  "Shahid - Ahmali",
  "Shalawi Transport",
  "Shamoos Logistics",
  "Shams Al khaleej - Gulf Sun",
  "Shorouk al kharj transport",
  "Shroq al Khaleej Transport",
  "Silk Road Logistics",
  "Silver Square",
  "Sitco Logistics",
  "Skyline Global Shipping",
  "Smart Supplies For Logistics",
  "Smart Vision (M Ali Faiz)",
  "Solution Makers International (SMI)",
  "Soor Al Azeem",
  "Starlinks Logistics",
  "Sulaiman Hamad Est",
  "Suliman Al Hajri Transport",
  "Sultan Al Saudi Establishment",
  "Sultan Mohammed Nawash Est. for transport",
  "Syrve",
  "TAJ AL AROOBA",
  "TARIQ",
  "TARIQ MEHMOOD",
  "TOUHEED",
  "TRUCKIT CARGO TRANSPORT BY HEAVY",
  "TURUK AL TAWEEL",
  "Taazur Transportation",
  "Taqniat Tamaiyaz",
  "Tariq Albdyah Est",
  "Tariq dirver Champion",
  "Taychon",
  "Taysert",
  "Teles Transport",
  "Teqniyat Aljawadah transport",
  "Testing",
  "Thiqat Alekhtiar Transport",
  "Transport Masarat Al Sareaa",
  "Transportation Lines",
  "Trell.app",
  "Trella Domestic Group",
  "Trella Rentals",
  "Trella Saudi",
  "Trella UAE",
  "Trella Unconfirmed",
  "Trellah Cash TH",
  "Truxat company",
  "USAMA",
  "USMAN",
  "UTC Logistics",
  "Vault Logistics Services",
  "WAHEED KSA TRANSPORT",
  "WD LOGISTIC",
  "WLD Logistics",
  "Waleed A.Al- Homedi Est.",
  "Waleed Alrashdi",
  "Waleed Mohammad transportation",
  "Walid Al-Sawat Transport Corporation",
  "Waqar Itruck",
  "Waqoodi Transportation",
  "Wared Transportation LTD",
  "Washm Transport",
  "Wasie For Transporting Est.",
  "Wasl Saudia Co. Ltd",
  "Waston Transportation",
  "Wejhat Rental",
  "Wejhat Transport",
  "Welcome@2022",
  "West Group",
  "Western Trust Transport",
  "Wolf Transport",
  "Worldwide Logistics Systems",
  "Worldwide Riyadh",
  "Yaqoub",
  "Yasen abdulkarim",
  "Yousif (Bin rabi transport company)",
  "Yunos (MStar) IO Champion",
  "ZAHEER AFZAL TRANSPORT LLC",
  "ZAID AHMED CARGO",
  "Ziyad Homud Al Hazmy Transport Est.",
  "aaa",
  "al Jabri empties",
  "al adwaani",
  "alafaliq",
  "ana",
  "balaj champion",
  "bnaa alastol",
  "brothers",
  "champion",
  "defaf united for logistics co",
  "eng",
  "faiza223190",
  "first middle east",
  "g",
  "haji champion",
  "hh",
  "jfr",
  "mohammed",
  "mozarilla",
  "mtaya aldrob",
  "nadi champion",
  "no name",
  "rk centenar services",
  "tawfik",
  "tayseer Transport",
  "trella saudi ",
  "tsc",
  "wasco",
  "؛GYS",
  "احمد صبري سرساوي",
  "السعيد للنقل",
  "الشحنة الاولى للنقل البري",
  "الصفوه",
  "المواد النقية",
  "شركة الريف للنقليات",
  "شركة الزرعة",
  "عادل عوض ابن سويلم",
  "مؤسسة سطام فهد المطيري",
  "مؤسسة نماء وبناء للمقاوالت",
  "موئسسة العريقة",
  "موسسة الخريف",
  "موسسه سعد عبد الحميد الصبحي",
  "موسسه شروق الجزيره",
  "موسسه عيسى العدواني لنقليات",
  "موسسه هبوب نجد لنقليات",
  "نقليات المصدر الحديث",
]

async function main() {
  console.log('Clearing existing suppliers...')

  // First check if any suppliers are referenced in commitments
  const commitmentsCount = await prisma.supplyCommitment.count()
  if (commitmentsCount > 0) {
    console.log(`Warning: ${commitmentsCount} supply commitments exist. Deleting them first...`)
    await prisma.supplyCommitment.deleteMany()
  }

  // Delete all existing suppliers
  await prisma.supplier.deleteMany()
  console.log('Deleted all existing suppliers')

  // Add new suppliers using batch insert (much faster)
  console.log(`Adding ${suppliers.length} fleet partners...`)
  const uniqueSuppliers = [...new Set(suppliers.map(s => s.trim()).filter(s => s.length > 0))]

  // Use createMany for batch insert
  await prisma.supplier.createMany({
    data: uniqueSuppliers.map(name => ({ name, isActive: true })),
    skipDuplicates: true,
  })

  const finalCount = await prisma.supplier.count()
  console.log(`Successfully added ${finalCount} fleet partners!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
